steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/spinoff-group-library-site/library', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/spinoff-group-library-site/library']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'library', '--image', 'gcr.io/spinoff-group-library-site/library', '--region', 'australia-southeast1']
images:
- gcr.io/spinoff-group-library-site/library